version: '3.3'

services:
  anfeb:
    image: "anfeb"
    stop_signal: SIGINT
    build:
      context: .
    working_dir: "/usr/src/app/anfeb"
    volumes:
      - anfeb-data:/usr/src/app/anfeb/data
    restart: always
    env_file:
      - ".env"

volumes:
  anfeb-data: